name: Playwright Tests with GUI

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install playwright  # Install Playwright

      # Step 4: Install Xvfb (X Virtual Framebuffer)
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      # Step 5: Run Playwright tests with GUI support
      - name: Run Playwright tests
        run: |
          Xvfb :99 &  # Start Xvfb (virtual display)
          export DISPLAY=:99  # Set the display environment variable
          npx playwright test  # Run Playwright tests
